name: Magento UI autotests

on: 

jobs:
  autotests:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python 
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Set up test environment
        run: pip install -r requirements.txt
      - name: Start tests
        run: pytest
