name: Magento UI autotests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Select test set
        required: true
        type: choice
        default: regression
        options:
          - all
          - extended
          - regression
          - smoke    

jobs:
  autotests:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python 
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Set up test environment
        run: pip install -r requirements.txt
      - name: Run all tests
        if: 'github.event.inputs.deployment_target == "all"'
        run: pytest --alluredir=allure-results
      - name: Run extended test set
        if: 'github.event.inputs.deployment_target == "extended"'
        run: pytest -m extended
      - name: Run regression test set
        if: 'github.event.inputs.deployment_target == "regression"'
        run: pytest -m regression
      - name: Run smoke test set
        if: 'github.event.inputs.deployment_target == "smoke"'
        run: pytest -m smoke
        
